function y = highPassChebyshev1Filt_EEG(x, fs)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.3 and DSP System Toolbox 9.5.
% Generated on: 02-Oct-2017 12:46:13

persistent Hd;

if isempty(Hd)
    
    Fstop = 0.01;  % Stopband Frequency
    Fpass = .5;     % Passband Frequency
    Astop = 25;    % Stopband Attenuation (dB)
    Apass = 3;     % Passband Ripple (dB)
    Fs    = fs;   % Sampling Frequency
    
    h = fdesign.highpass('fst,fp,ast,ap', Fstop, Fpass, Astop, Apass, Fs);
    
    Hd = design(h, 'cheby1', ...
        'MatchExactly', 'passband');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);

